#!/usr/bin/env python3
"""
Regenerate docs/src/std/*.md pages from the live stdlib source.

Each generated page is a thin wrapper: title, one-line summary
extracted from the .ap file's leading comment, then an mdbook
{{#include}} of the .ap file inside an `aperio` fence.

Pages for modules without an .ap file (e.g. env, str, time —
not yet implemented) are not generated; their existing prose
pages are roadmap/spec content and are left alone.
"""

import os, re, sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
STDLIB = os.path.join(REPO, "crates", "aperio-codegen", "runtime", "stdlib")
DOCS_STD = os.path.join(REPO, "docs", "src", "std")

# stdlib-file -> doc-page path (relative to docs/src/std/)
PAGE_MAP = {
    "cli.ap":     "cli.md",
    "core.ap":    "core.md",
    "http.ap":    "http.md",
    "io_tcp.ap":  "io/tcp.md",
    "iter.ap":    "iter.md",
    "json.ap":    "json.md",
    "lang.ap":    "lang.md",
    "log.ap":     "log.md",
    "name.ap":    "name.md",
    "source.ap":  "source.md",
    "tagged.ap":  "tagged.md",
    "test.ap":    "test.md",
    "text.ap":    "text.md",
    "ts.ap":      "ts.md",
}

# Title for the doc-page H1
TITLE_MAP = {
    "cli.ap":     "`std::cli`",
    "core.ap":    "`std::core`",
    "http.ap":    "`std::http`",
    "io_tcp.ap":  "`std::io::tcp`",
    "iter.ap":    "`std::iter`",
    "json.ap":    "`std::json`",
    "lang.ap":    "`std::lang`",
    "log.ap":     "`std::log`",
    "name.ap":    "`std::name`",
    "source.ap":  "`std::source`",
    "tagged.ap":  "`std::tagged`",
    "test.ap":    "`std::test`",
    "text.ap":    "`std::text`",
    "ts.ap":      "`std::ts`",
}

def first_comment_paragraph(src):
    """First contiguous `// ...` block, as a single trimmed string."""
    lines = []
    for line in src.splitlines():
        s = line.strip()
        if s.startswith("//"):
            stripped = s[2:].lstrip()
            if not stripped:
                if lines:
                    break  # first paragraph ended
                continue
            lines.append(stripped)
        elif lines:
            break
        elif s == "":
            continue
        else:
            break
    return " ".join(lines).strip()

def page_body(ap_name, ap_path, page_rel):
    title = TITLE_MAP[ap_name]
    with open(ap_path) as f:
        src = f.read()
    summary = first_comment_paragraph(src)
    # depth from docs/src/std/<page_rel> back to repo root
    depth = page_rel.count("/") + 3  # std + src + docs
    up = "../" * depth
    include_path = f"{up}crates/aperio-codegen/runtime/stdlib/{ap_name}"
    parts = [
        f"# {title}",
        "",
        f"> {summary}" if summary else "",
        "",
        "The source for this module is the documentation; the page is regenerated by",
        "`docs/scripts/regen-std-source.py` from the live stdlib source.",
        "",
        "```aperio",
        "{{#include " + include_path + "}}",
        "```",
        "",
    ]
    return "\n".join(p for p in parts if p is not None)

def main():
    written = []
    for ap_name, page_rel in PAGE_MAP.items():
        ap_path = os.path.join(STDLIB, ap_name)
        if not os.path.exists(ap_path):
            print(f"skip: {ap_path} does not exist", file=sys.stderr)
            continue
        page_path = os.path.join(DOCS_STD, page_rel)
        os.makedirs(os.path.dirname(page_path), exist_ok=True)
        with open(page_path, "w") as f:
            f.write(page_body(ap_name, ap_path, page_rel))
        written.append(page_rel)
    print(f"wrote {len(written)} pages: {', '.join(written)}")

if __name__ == "__main__":
    main()
