// Generated by `hale api client --surface Todo --lang ts` from the rows of the surface
// Todo (fnv1a64:67bff1470a7912dc). Do not edit: regenerate it, and `hale api client --check` refuses a
// copy whose digest is no longer the surface's. See spec/api.md § The clients.
//
// One async function per member, `<locus><Fn>(opts, request)`, answering the tagged union of
// `result`, `handler_error`, `refusal` and `server_error`; a connection that never answered is
// thrown as a TransportError. A quantity, an identity or a range crosses as the number it counts
// (an Int past 2^53 loses precision as a JSON number does in JavaScript).

export const SURFACE = "Todo";
export const SURFACE_DIGEST = "fnv1a64:67bff1470a7912dc";

// ---- the wire, as every client of a surface speaks it (spec/api.md § The clients) ----
//
// Depends on `fetch` and `WebSocket` and nothing else. An endpoint is
// `http://host:port` for a member's call and `ws://host:port` (a hub) for a
// stream; a socket is not spoken (`fetch` has none). A call sends the
// surface's digest in `Hale-Surface-Digest` and answers one of four outcomes;
// the fifth, a connection that never answered, is thrown as a TransportError,
// because a request that may have been accepted is not a refusal.

// The globals the wire names as types, reached through `globalThis` so that no type of the surface (a
// `Response`, a `Record`, a `Promise`) can shadow one: a module's own declarations win over the
// global scope, and `globalThis.X` is the one spelling they do not reach.
type __Record<K extends keyof any, V> = globalThis.Record<K, V>;
type __Promise<T> = globalThis.Promise<T>;
type __Array<T> = globalThis.Array<T>;
type __AsyncIterable<T> = globalThis.AsyncIterable<T>;
type __AsyncGenerator<T> = globalThis.AsyncGenerator<T>;
type __Response = globalThis.Response;
type __MessageEvent = globalThis.MessageEvent;

export interface ClientOptions {
  /** `http://host:port` of an `http::Rpc` listener (or of a hub's listener). */
  endpoint: string;
  /** The bearer token, sent as `Authorization: Bearer`. */
  bearer?: string;
  /** A `fetch` to use instead of the global one. */
  fetch?: typeof fetch;
}

export interface StreamOptions {
  /** `ws://host:port` of a hub. */
  endpoint: string;
  /** The bearer token, sent as `?access_token=` (a browser cannot set a header on a WebSocket). */
  bearer?: string;
  /** A `WebSocket` constructor to use instead of the global one. */
  WebSocket?: typeof WebSocket;
}

/** A refusal: the request was not run (spec/api.md § Outcomes). */
export interface Refusal {
  /** `malformed`, `digest_mismatch`, `unauthenticated`, `unauthorized`, `full`, `shutting_down` or `unavailable`. */
  kind: string;
  reason: string;
  /** The roles a refused row requires. */
  requires: string[];
  /** The digest the server holds, for `digest_mismatch`. */
  served?: string;
}

/** The connection ended, or answered no outcome: the request may or may not have run. */
export class TransportError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TransportError";
  }
}

export type Outcome<T, E> =
  | { kind: "result"; value: T }
  | { kind: "handler_error"; error: E }
  | { kind: "refusal"; refusal: Refusal }
  | { kind: "server_error" };

function apiRefusal(body: unknown): Refusal {
  const r = (body as { refusal?: __Record<string, unknown> } | null)?.refusal ?? {};
  const out: Refusal = {
    kind: typeof r.kind === "string" ? r.kind : "malformed",
    reason: typeof r.reason === "string" ? r.reason : "",
    requires: Array.isArray(r.requires) ? r.requires.map(String) : [],
  };
  if (typeof r.served === "string") out.served = r.served;
  return out;
}

async function apiCall<T, E>(
  opts: ClientOptions,
  member: string,
  payload: string,
  decodeValue: (json: unknown) => T,
  decodeError: (json: unknown) => E,
): __Promise<Outcome<T, E>> {
  const headers: __Record<string, string> = {
    "Content-Type": "application/json",
    "Hale-Surface-Digest": SURFACE_DIGEST,
  };
  if (opts.bearer) headers["Authorization"] = "Bearer " + opts.bearer;
  let res: __Response;
  let text: string;
  try {
    res = await (opts.fetch ?? fetch)(opts.endpoint + "/call/" + member, { method: "POST", headers, body: payload });
    text = await res.text();
  } catch (e) {
    throw new TransportError("the endpoint " + opts.endpoint + " cannot be reached: " + String(e));
  }
  let body: unknown = null;
  try {
    body = text.length > 0 ? JSON.parse(text) : null;
  } catch {
    throw new TransportError("the endpoint answered " + res.status + " with no JSON: " + text);
  }
  if (res.status === 200) return { kind: "result", value: decodeValue(body) };
  if (res.status === 422) return { kind: "handler_error", error: decodeError(body) };
  const refusal = apiRefusal(body);
  if ((body as { refusal?: unknown } | null)?.refusal === undefined) {
    throw new TransportError("the endpoint answered " + res.status + " with no outcome: " + text);
  }
  if (refusal.kind === "server") return { kind: "server_error" };
  return { kind: "refusal", refusal };
}

/** The description the endpoint serves this caller, as parsed JSON. */
export async function describe(opts: ClientOptions): __Promise<unknown> {
  const headers: __Record<string, string> = { Accept: "application/json" };
  if (opts.bearer) headers["Authorization"] = "Bearer " + opts.bearer;
  try {
    const res = await (opts.fetch ?? fetch)(opts.endpoint + "/.description", { headers });
    return JSON.parse(await res.text());
  } catch (e) {
    throw new TransportError("the description of " + opts.endpoint + " cannot be read: " + String(e));
  }
}

// ---- streams over a hub ----

/** What a subscription yields; it ends after `refusal`, `expired`, `revoked` or `closed`. */
export type StreamEvent<P> =
  | { kind: "subscribed" }
  | { kind: "event"; seq: number; payload: P }
  | { kind: "refusal"; refusal: Refusal }
  | { kind: "expired" }
  | { kind: "revoked" }
  | { kind: "closed" };

export interface Subscription<P> extends __AsyncIterable<StreamEvent<P>> {
  /** Ends the subscription and closes the connection. */
  close(): void;
}

function apiSubscribe<P>(opts: StreamOptions, topic: string, decode: (json: unknown) => P): Subscription<P> {
  const queue: __Array<StreamEvent<P> | TransportError | null> = [];
  let wake: (() => void) | undefined;
  let ended = false;
  const push = (item: StreamEvent<P> | TransportError | null): void => {
    queue.push(item);
    if (wake) {
      const w = wake;
      wake = undefined;
      w();
    }
  };
  const url = new URL(opts.endpoint);
  if (opts.bearer) url.searchParams.set("access_token", opts.bearer);
  const ws = new (opts.WebSocket ?? WebSocket)(url.toString());
  const finish = (): void => {
    if (ended) return;
    ended = true;
    push(null);
    try {
      ws.close();
    } catch {
      /* already closed */
    }
  };
  const lose = (why: string): void => {
    if (ended) return;
    ended = true;
    push(new TransportError(why));
    push(null);
  };
  ws.onopen = () => ws.send(JSON.stringify({ type: "subscribe", topic }));
  ws.onmessage = (m: __MessageEvent) => {
    if (ended) return;
    let frame: __Record<string, unknown>;
    try {
      frame = JSON.parse(String(m.data)) as __Record<string, unknown>;
    } catch {
      return lose("the hub sent a frame that is not JSON: " + String(m.data));
    }
    if (frame.type !== "closed" && frame.topic !== undefined && frame.topic !== topic) return;
    switch (frame.type) {
      case "subscribed":
        return push({ kind: "subscribed" });
      case "event":
        return push({ kind: "event", seq: Number(frame.seq), payload: decode(frame.payload) });
      case "refusal":
        push({ kind: "refusal", refusal: apiRefusal(frame) });
        return finish();
      case "unauthorized":
        push({ kind: frame.reason === "expired" ? "expired" : "revoked" });
        return finish();
      case "closed":
        push({ kind: "closed" });
        return finish();
      default:
        return;
    }
  };
  ws.onerror = () => lose("the hub at " + opts.endpoint + " cannot be reached");
  ws.onclose = () => lose("the hub ended the connection with no closed frame");
  return {
    close: finish,
    async *[Symbol.asyncIterator](): __AsyncGenerator<StreamEvent<P>> {
      for (;;) {
        while (queue.length === 0) await new Promise<void>((resolve) => (wake = resolve));
        const item = queue.shift();
        if (item === null || item === undefined) return;
        if (item instanceof TransportError) throw item;
        yield item;
      }
    },
  };
}

export interface AddTodo {
  title: string;
  due: string;
}

export function encode_AddTodo(v: AddTodo): unknown {
  return {
    title: v.title,
    due: v.due,
  };
}

export function decode_AddTodo(json: unknown): AddTodo {
  const o = (json ?? {}) as __Record<string, unknown>;
  return {
    title: String(o["title"] ?? ""),
    due: String(o["due"] ?? ""),
  };
}

export interface Change {
  what: string;
  item: TodoItem;
}

export function encode_Change(v: Change): unknown {
  return {
    what: v.what,
    item: encode_TodoItem(v.item),
  };
}

export function decode_Change(json: unknown): Change {
  const o = (json ?? {}) as __Record<string, unknown>;
  return {
    what: String(o["what"] ?? ""),
    item: decode_TodoItem(o["item"]),
  };
}

export interface ListQuery {
  open_only: boolean;
}

export function encode_ListQuery(v: ListQuery): unknown {
  return {
    open_only: v.open_only,
  };
}

export function decode_ListQuery(json: unknown): ListQuery {
  const o = (json ?? {}) as __Record<string, unknown>;
  return {
    open_only: (o["open_only"] ?? false) === true,
  };
}

export interface Nothing {
}

export function encode_Nothing(v: Nothing): unknown {
  return {
  };
}

export function decode_Nothing(json: unknown): Nothing {
  const o = (json ?? {}) as __Record<string, unknown>;
  return {
  };
}

export interface TodoError {
  code: string;
  reason: string;
}

export function encode_TodoError(v: TodoError): unknown {
  return {
    code: v.code,
    reason: v.reason,
  };
}

export function decode_TodoError(json: unknown): TodoError {
  const o = (json ?? {}) as __Record<string, unknown>;
  return {
    code: String(o["code"] ?? ""),
    reason: String(o["reason"] ?? ""),
  };
}

export interface TodoItem {
  id: number;
  title: string;
  done: boolean;
  due: string;
  overdue: boolean;
}

export function encode_TodoItem(v: TodoItem): unknown {
  return {
    id: v.id,
    title: v.title,
    done: v.done,
    due: v.due,
    overdue: v.overdue,
  };
}

export function decode_TodoItem(json: unknown): TodoItem {
  const o = (json ?? {}) as __Record<string, unknown>;
  return {
    id: Number(o["id"] ?? 0),
    title: String(o["title"] ?? ""),
    done: (o["done"] ?? false) === true,
    due: String(o["due"] ?? ""),
    overdue: (o["overdue"] ?? false) === true,
  };
}

export interface TodoList {
  count: number;
  json: string;
}

export function encode_TodoList(v: TodoList): unknown {
  return {
    count: v.count,
    json: v.json,
  };
}

export function decode_TodoList(json: unknown): TodoList {
  const o = (json ?? {}) as __Record<string, unknown>;
  return {
    count: Number(o["count"] ?? 0),
    json: String(o["json"] ?? ""),
  };
}

export interface TodoRef {
  todo: number;
}

export function encode_TodoRef(v: TodoRef): unknown {
  return {
    todo: v.todo,
  };
}

export function decode_TodoRef(json: unknown): TodoRef {
  const o = (json ?? {}) as __Record<string, unknown>;
  return {
    todo: Number(o["todo"] ?? 0),
  };
}

/** Todos::add, requires editor */
export type TodosAddOutcome = Outcome<TodoItem, TodoError>;

export function todosAdd(opts: ClientOptions, request: AddTodo): __Promise<TodosAddOutcome> {
  return apiCall(opts, "Todos::add", JSON.stringify(encode_AddTodo(request)), (json) => decode_TodoItem(json), (json) => decode_TodoError(json));
}

/** Todos::complete, requires editor */
export type TodosCompleteOutcome = Outcome<TodoItem, TodoError>;

export function todosComplete(opts: ClientOptions, request: TodoRef): __Promise<TodosCompleteOutcome> {
  return apiCall(opts, "Todos::complete", JSON.stringify(encode_TodoRef(request)), (json) => decode_TodoItem(json), (json) => decode_TodoError(json));
}

/** Todos::list, requires reader */
export type TodosListOutcome = Outcome<TodoList, never>;

export function todosList(opts: ClientOptions, request: ListQuery): __Promise<TodosListOutcome> {
  return apiCall(opts, "Todos::list", JSON.stringify(encode_ListQuery(request)), (json) => decode_TodoList(json), () => { throw new TransportError("the member has no handler error, and one came"); });
}

/** Todos::overdue, requires reader */
export type TodosOverdueOutcome = Outcome<TodoList, never>;

export function todosOverdue(opts: ClientOptions, request: Nothing): __Promise<TodosOverdueOutcome> {
  return apiCall(opts, "Todos::overdue", JSON.stringify(encode_Nothing(request)), (json) => decode_TodoList(json), () => { throw new TransportError("the member has no handler error, and one came"); });
}

/** Todos::remove, requires editor */
export type TodosRemoveOutcome = Outcome<TodoItem, TodoError>;

export function todosRemove(opts: ClientOptions, request: TodoRef): __Promise<TodosRemoveOutcome> {
  return apiCall(opts, "Todos::remove", JSON.stringify(encode_TodoRef(request)), (json) => decode_TodoItem(json), (json) => decode_TodoError(json));
}

/** The stream TodoChanged of the hub stream (stream digest fnv1a64:1768fa8b8fd4c428), requires reader: `subscribed`, then
 * each `event` with its `seq` (a gap is the frames shed) until `expired`, `revoked` or `closed`; a
 * connection that ends with no closed frame throws a TransportError from the iterator. */
export type TodoChangedEvent = StreamEvent<Change>;

export function subscribeTodoChanged(opts: StreamOptions): Subscription<Change> {
  return apiSubscribe(opts, "TodoChanged", (json) => decode_Change(json));
}
